version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: gastify-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    environment:
      - MONGO_URI=mongodb://mongo:27017/gastify
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - mongo
      - redis
    networks:
      - gastify-network

  web:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: gastify-web
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Use named volume for node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - HOST=0.0.0.0  # Configurar host para acceso externo
    depends_on:
      - api
    networks:
      - gastify-network

  mongo:
    image: mongo:6.0
    container_name: gastify-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - gastify-network

  redis:
    image: redis:alpine
    container_name: gastify-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gastify-network

networks:
  gastify-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data: